'use client';

import { useState } from 'react';
import { Share2, Copy, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';

export function ShareButton({ slug, repoName }: { slug: string, repoName: string }) {
    const [copied, setCopied] = useState(false);

    const handleShare = async () => {
        const url = `${window.location.origin}/analysis/${slug}`;
        
        if (navigator.share) {
            try {
                await navigator.share({
                    title: `Codebase Analysis: ${repoName}`,
                    text: `Check out this deep architectural analysis of ${repoName} generated by CheckBeforeCommit.`,
                    url: url,
                });
            } catch (err) {
                // User cancelled or share failed, fallback to copy
                copyToClipboard(url);
            }
        } else {
            // Fallback for browsers without Web Share API
            copyToClipboard(url);
        }
    };

    const copyToClipboard = async (text: string) => {
        try {
            await navigator.clipboard.writeText(text);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (err) {
            console.error('Failed to copy text: ', err);
        }
    };

    return (
        <Button 
            onClick={handleShare} 
            size="sm"
            className="bg-primary/10 hover:bg-primary/20 text-primary border border-primary/20 font-bold flex items-center gap-2"
        >
            {copied ? (
                <>
                    <CheckCircle2 className="w-4 h-4 text-green-500" />
                    <span className="text-green-600">Copied!</span>
                </>
            ) : (
                <>
                    <Share2 className="w-4 h-4" />
                    <span>Share Report</span>
                </>
            )}
        </Button>
    );
}
